# Generated by Django 6.0.5 on 2026-05-21 23:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id_ban', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, default='', max_length=10)),
                ('rep', models.CharField(blank=True, default='', max_length=10)),
                ('nom_voie', models.CharField(blank=True, default='', max_length=300)),
                ('code_postal', models.CharField(blank=True, default='', max_length=5)),
                ('code_insee', models.CharField(blank=True, default='', max_length=5)),
                ('nom_commune', models.CharField(blank=True, default='', max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('cad_parcelles', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('code_insee', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=5)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='cadastre.departement')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('idu', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('contenance', models.IntegerField(db_index=True)),
                ('prefixe', models.CharField(max_length=3)),
                ('section', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=4)),
                ('arpente', models.BooleanField(default=False)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='cadastre.commune')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles_rel', to='cadastre.adresse')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_rel', to='cadastre.parcelle')),
            ],
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['commune', 'contenance'], name='cadastre_pa_commune_a29b4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelleadresse',
            unique_together={('parcelle', 'adresse')},
        ),
    ]
