# Generated by Django 6.0.5 on 2026-05-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0002_remove_unused_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='has_address',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
