# Generated by Django 6.0.5 on 2026-05-25 15:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0003_add_has_address_to_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='commune',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='cadastre.commune'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(spatial_index=False, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcelleadresse',
            name='parcelle',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='adresses_rel', to='cadastre.parcelle'),
        ),
    ]
