# Generated by Django 6.0.5 on 2026-05-25 15:52

from django.db import migrations, models


def populate_nb_parcelles_adresse(apps, schema_editor):
    Departement = apps.get_model("cadastre", "Departement")
    Parcelle = apps.get_model("cadastre", "Parcelle")
    for dep in Departement.objects.all():
        dep.nb_parcelles_adresse = Parcelle.objects.filter(
            commune__departement=dep, has_address=True
        ).count()
        dep.save(update_fields=["nb_parcelles_adresse"])


def reverse_nb_parcelles_adresse(apps, schema_editor):
    Departement = apps.get_model("cadastre", "Departement")
    Departement.objects.update(nb_parcelles_adresse=0)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0004_alter_parcelle_commune_alter_parcelle_geometry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='nb_parcelles_adresse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['commune', 'has_address'], name='cadastre_pa_commune_d89268_idx'),
        ),
        migrations.RunPython(
            populate_nb_parcelles_adresse, reverse_nb_parcelles_adresse
        ),
    ]
